### ISSUE TITLE
Examples or documentation

### ISSUE THREAD

**Issue by MarsVard** [octiplex/Android-RTMP-Muxer#2]
Hello

I'm having difficulty using this library, Is there an example project or a more extended documentation available?

How would an url like this be user with this library?
What is the meaning of serverUrl, pageUrl, application?
rtmp://rtmp-api.facebook.com:80/rtmp/10656346080699666?ds=1&s_l=1&a=xTxRpuj_8A2xtHy-

Thank you

**Comment by benoitletondor** [comment]
Hello there.

For an exemple, you can check this project that is using this library to stream the phone screen to an RTMP server: https://github.com/insthync/AndroidSimpleScreenRTMP2

Here's the detail for your url:

- `host`: rtmp-api.facebook.com
- `port`: 80
- `app`: rtmp
- `playpath`: 10656346080699666?ds=1&s_l=1&a=xTxRpuj_8A2xtHy-

So to use the muxer, create it using the constructor: 

```
mMuxer = new RtmpMuxer("rtmp-api.facebook.com", 80, time);
```

Start the muxer with the following parameters:

```
mMuxer.start(listener, "rtmp", null, null);
```

Then create the stream:

```
mMuxer.createStream("10656346080699666?ds=1&s_l=1&a=xTxRpuj_8A2xtHy-");
```

Hope it answers your questions.

**Comment by MarsVard** [comment]
Thank you for the feedback @benoitletondor It's clear now and working but for some reason the frame rate is very low on the rtmp output, like 1 frame per 5 minutes and the library throws this after a few seconds of recording.
```
Ack received from server after 5038026 bytes. We sent 10192201 bytes, the server saw 10001863 bytes
...
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
```

**Comment by benoitletondor** [comment]
Hi @MarsVard,

Hum this is strange. Usually a server closing the connexion means an error occurred: the server cannot read a received message or didn't received an expected message.

The library hasn't been tested against Facebook RTMP servers so maybe my implementation isn't correct for a specific part and the Ngnix RTMP module (the one I tested against) doesn't mind.

I can't really help you more on that, but if you find a bug please submit a PullRequest and I'll be happy to review it :)

**Comment by benoitletondor** [comment]
@MarsVard And don't forget to (at least) close the issue if you find the reason 😉  I'm really curious about the problem and your workaround so let me know!

Thanks!

**Comment by Chococrok** [comment]
Hi we are a groupe of students from Toulouse trying to stream on facebook but we have the same difficulties as @MarsVard . 
We were wondering since audio is apparently mandatory, (https://developers.facebook.com/docs/videos/live-video/troubleshootlive) how do you implement the sound with your library. I am sorry but we couldn't find out how to parse AAC and so on. So if could explain us this part that would be great :) 
Thanks

**Comment by benoitletondor** [comment]
Hi @Chococrok,

The README provide with an exemple of how to use `MediaRecorder` to record audio from Android, but this repo doesn't cover how to parse AAC ADTS chunks since it's a whole different topic and often not trivial.

You can find some open sources implementation of AAC parsing, like this one: http://jaadec.sourceforge.net/ to inspire you.

Bonne chance !

**Comment by Chococrok** [comment]
Ok I will dig more into that !

Merci !

**Comment by ankitKamboj121** [comment]
Hello @benoitletondor , when i run this code: https://github.com/insthync/AndroidSimpleScreenRTMP2 and hit start recording button,
the app crashes. Any help?

**Comment by benoitletondor** [comment]
Hi, can you post the crash log with the stacktrace?

**Comment by ankitKamboj121** [comment]
This is the error:
 java.lang.IllegalStateException: You must wait for listener onReadyToPublish() to be called before calling deleteSteam

from RtmpMuxer class. Please check.

**Comment by ankitKamboj121** [comment]
Can you provide the full working app of https://github.com/octiplex/Android-RTMP-Muxer
As how it works because I need to integrate this functionality in one of my app.

**Comment by benoitletondor** [comment]
I can't provide anything more than what is on this repo, plus I'm not working at Octiplex anymore so it's all I have access to.

As for your crash, I'm pretty sure it's because the app targets an RTMP server that is not live anymore so it can't connect. So when you push the record button again to stop the stream it crashes as it can't stop a stream that wasn't started first.

**Comment by de-gall** [comment]
Hello

I'm having difficulty using this library, Is there an example project or a more extended documentation available?

How would an url like this be user with this library?
What is the meaning of serverUrl, pageUrl, application?
rtmp://a.rtmp.youtube.com/live2/wjv3-euek-p52u-96jw

Thank you

**Comment by benoitletondor** [comment]
Hi, I'm not working on the project anymore but here's a little help on your URL:

host: a.rtmp.youtube.com
port: 1935
app: live2
playpath: wjv3-euek-p52u-96jw

**Comment by de-gall** [comment]
thank you very much, I had already found the solution, but I have another problem the basicheader is equal to 66 or 0 in my case
