### ISSUE TITLE
API too Complicated 

### ISSUE THREAD

**Issue by ChillingVan** [octiplex/Android-RTMP-Muxer#3]
Hi, I want to use this library but the APIs are too complicated... You can see this project 
https://github.com/ant-media/LibRtmp-Client-for-Android
No URI parse , just a String for url.

Do not need to wait for the ready pubilsh thing.

And thanks for the information about RTMP protocal. You can totally put it on jitpack after optimizing.

**Comment by benoitletondor** [comment]
Hi @ChillingVan !

Thank you for the suggestion. Actually, the API of this project is complicated due to the fact that it follows RTMP implementation: all those steps are imposed by the protocol and an error can be thrown at any stage and thus needs to be handled properly.

Meanwhile, the project is open source and if you feel like providing a wrapper around it to simplify APIs feel free to do so.
